export const PREVIEW_EMPRESA = {
  nombre: 'Soluciones Digitales S.L.',
  nif: 'B12345678',
  direccion: 'Calle Gran Vía 42, 3ª Planta',
  codigoPostal: '28013',
  ciudad: 'Madrid',
  provincia: 'Madrid',
  telefono: '912 345 678',
  email: 'info@solucionesdigitales.es',
  web: 'www.solucionesdigitales.es',
}

export const PREVIEW_FACTURACION = {
  piePagina: 'Gracias por confiar en nosotros. Pago a 30 días mediante transferencia bancaria.',
}

export const PREVIEW_FACTURA: Factura = {
  id: 0,
  numero: 'F2026-0042',
  serie: 'F',
  fecha: new Date('2026-02-15'),
  fechaVencimiento: new Date('2026-03-17'),
  clienteId: 1,
  cliente: {
    id: 1,
    nombre: 'Cliente de Ejemplo S.L.',
    nif: 'A87654321',
    email: 'contacto@clienteejemplo.es',
    telefono: '913 456 789',
    direccion: 'Avda. de la Constitución 15',
    codigoPostal: '28045',
    ciudad: 'Madrid',
    provincia: 'Madrid',
    pais: 'España',
    notas: null,
    activo: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  subtotal: 1850.00,
  totalImpuestos: 388.50,
  totalRetenciones: 0,
  total: 2238.50,
  estado: 'enviada',
  notas: 'Proyecto de desarrollo web - Fase 1. Incluye diseño, maquetación y programación del frontend.',
  formaPago: 'transferencia',
  createdAt: new Date(),
  updatedAt: new Date(),
  lineas: [
    {
      id: 1,
      facturaId: 0,
      productoId: null,
      producto: null,
      descripcion: 'Diseño y desarrollo web',
      cantidad: 1,
      precioUnit: 1200.00,
      descuento: 0,
      impuestoId: 1,
      impuesto: { id: 1, nombre: 'IVA General', porcentaje: 21, tipo: 'IVA', activo: true, porDefecto: true, createdAt: new Date(), updatedAt: new Date() },
      retencionId: null,
      retencion: null,
      subtotal: 1200.00,
      totalImpuesto: 252.00,
      totalRetencion: 0,
      total: 1452.00,
    },
    {
      id: 2,
      facturaId: 0,
      productoId: null,
      producto: null,
      descripcion: 'Consultoría SEO',
      cantidad: 5,
      precioUnit: 80.00,
      descuento: 0,
      impuestoId: 1,
      impuesto: { id: 1, nombre: 'IVA General', porcentaje: 21, tipo: 'IVA', activo: true, porDefecto: true, createdAt: new Date(), updatedAt: new Date() },
      retencionId: null,
      retencion: null,
      subtotal: 400.00,
      totalImpuesto: 84.00,
      totalRetencion: 0,
      total: 484.00,
    },
    {
      id: 3,
      facturaId: 0,
      productoId: null,
      producto: null,
      descripcion: 'Hosting anual',
      cantidad: 1,
      precioUnit: 250.00,
      descuento: 0,
      impuestoId: 1,
      impuesto: { id: 1, nombre: 'IVA General', porcentaje: 21, tipo: 'IVA', activo: true, porDefecto: true, createdAt: new Date(), updatedAt: new Date() },
      retencionId: null,
      retencion: null,
      subtotal: 250.00,
      totalImpuesto: 52.50,
      totalRetencion: 0,
      total: 302.50,
    },
  ],
}
